# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.3'

## Sorting

Q1. Sort x along the second axis.

In [7]:
x = np.array([[1,4],[3,1]])
out = np.sort(x, axis=1)
print (out)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [8]:
surnames = ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
print (np.lexsort((first_names, surnames)))

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [9]:
x = np.array([[1,4],[3,1]])
out = np.argsort(x, axis=1)
print (out)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [18]:
x = np.random.permutation(10)
print (x)
out = np.partition(x, 5)
print (out)


[3 6 9 2 7 5 0 8 1 4]
[0 3 1 2 4 5 6 7 9 8]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [22]:
x = np.random.permutation(10)
print ("x =", x)
partitioned = np.partition(x, 6)
indices = np.argpartition(x, 6)
print ("partitioned =", partitioned)
print ("indices =", partitioned)


x = [7 0 9 1 3 5 4 6 8 2]
partitioned = [1 2 0 3 4 5 6 7 8 9]
indices = [1 2 0 3 4 5 6 7 8 9]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [23]:
x = np.random.permutation(10).reshape(2, 5)
print ("x =", x)
print ("maximum values =", np.max(x, 1))
print ("max indices =", np.argmax(x, 1))
print ("minimum values =", np.min(x, 1))
print ("min indices =", np.argmin(x, 1))


x = [[9 4 0 6 3]
 [8 2 7 5 1]]
maximum values = [9 8]
max indices = [0 0]
minimum values = [0 1]
min indices = [2 4]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [24]:
x = np.array([[np.nan, 4], [3, 2]])
print ("maximum values ignoring NaNs =", np.nanmax(x, 1))
print ("max indices =", np.nanargmax(x, 1))
print ("minimum values ignoring NaNs =", np.nanmin(x, 1))
print ("min indices =", np.nanargmin(x, 1))

maximum values ignoring NaNs = [ 4.  3.]
max indices = [1 0]
minimum values ignoring NaNs = [ 4.  2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [26]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print ("Values bigger than 2 =", x[x>2])
print ("Their indices are ", np.nonzero(x > 2))

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [29]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print (np.flatnonzero(x))
print(x.ravel().nonzero())

[0 1 2 3 4 5]
(array([0, 1, 2, 3, 4, 5], dtype=int64),)


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [30]:
x = np.arange(-5, 4).reshape(3, 3)
print (np.where(x <0, 0, x))

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [31]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [33]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print (np.count_nonzero(x))
print(len(x[x!=0]))

5
5
